version: '3.7'

services:
  lighthouse:
    image: lighthouse-app:latest
    container_name: lighthouse-app
    restart: unless-stopped
    volumes:
      - ../lighthouse:/app
      - ../lighthouse/log:/var/log
    ports:
      - 127.0.0.1:5005:5000
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - lighthouse

  # mariadb:
  #   image: mariadb:10.4
  #   container_name: lighthouse-db
  #   restart: unless-stopped
  #   volumes:
  #     - ../lighthouse/db:/docker-entrypoint-initdb.d
  #     - ../lighthouse/secrets:/secrets
  #     - ../lighthouse-db/:/var/lib/mysql
  #   ports:
  #     - 127.0.0.1:3306:3306
  #   environment:
  #     - MYSQL_DATABASE=lighthouse
  #     - MYSQL_ROOT_PASSWORD_FILE=/secrets/mysql_password_root
  #     - MYSQL_USER_FILE=/secrets/mysql_user
  #     - MYSQL_PASSWORD_FILE=/secrets/mysql_password
  #   networks:
  #     - lighthouse

networks:
  lighthouse:
    driver: bridge
