version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  lighthouse:
    image: lighthouse-app:latest
    container_name: lighthouse-app
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./log:/var/log
      - /app/app/static/build/
    environment:
      - VIRTUAL_HOST=lighthouse.codetri.net
      - DOCKER_SECRETS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - lighthouse

  mariadb:
    image: mariadb:10.4
    container_name: lighthouse-db
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./secrets:/secrets
      - ../lighthouse-db/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=lighthouse
      - MYSQL_ROOT_PASSWORD_FILE=/secrets/mysql_password_root
      - MYSQL_USER_FILE=/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/secrets/mysql_password
    networks:
      - lighthouse

networks:
  lighthouse:
    driver: bridge
